FROM alpine:latest

# Install dependencies needed for CI tests
RUN apk add --no-cache make python3 py3-pexpect

# Copy entrypoint script
COPY entrypoint.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]